// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SiteReservationSystem.Web.Data;

#nullable disable

namespace SiteReservationSystem.Web.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260317200953_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SiteReservationSystem.Web.Models.Admin", b =>
                {
                    b.Property<int>("AdminID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AdminID"));

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("AdminID");

                    b.HasIndex("UserID")
                        .IsUnique();

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("SiteReservationSystem.Web.Models.Customer", b =>
                {
                    b.Property<int>("CustomerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerID"));

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("MilitaryAffiliation")
                        .HasColumnType("int");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("CustomerID");

                    b.HasIndex("UserID")
                        .IsUnique();

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("SiteReservationSystem.Web.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeID"));

                    b.Property<int>("AccessPermissions")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateHired")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsLockedOut")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("EmployeeID");

                    b.HasIndex("UserID")
                        .IsUnique();

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("SiteReservationSystem.Web.Models.Fee", b =>
                {
                    b.Property<int>("FeeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FeeID"));

                    b.Property<decimal>("DefaultAmount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FeeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("FeeID");

                    b.ToTable("Fees");

                    b.HasData(
                        new
                        {
                            FeeID = 1,
                            DefaultAmount = 25.00m,
                            Description = "Fee for checking out after designated time",
                            FeeName = "Late Checkout",
                            IsActive = true
                        },
                        new
                        {
                            FeeID = 2,
                            DefaultAmount = 15.00m,
                            Description = "Fee for checking in before standard time",
                            FeeName = "Early Check-in",
                            IsActive = true
                        },
                        new
                        {
                            FeeID = 3,
                            DefaultAmount = 10.00m,
                            Description = "Standard cancellation fee",
                            FeeName = "Cancellation Fee",
                            IsActive = true
                        });
                });

            modelBuilder.Entity("SiteReservationSystem.Web.Models.Invoice", b =>
                {
                    b.Property<int>("InvoiceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InvoiceID"));

                    b.Property<int>("CustomerID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DatePaid")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("InvoiceDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("ReservationID")
                        .HasColumnType("int");

                    b.Property<decimal>("SubTotal")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("TotalFees")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("InvoiceID");

                    b.HasIndex("CustomerID");

                    b.HasIndex("ReservationID")
                        .IsUnique();

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("SiteReservationSystem.Web.Models.Payment", b =>
                {
                    b.Property<int>("PaymentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentID"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("InvoiceID")
                        .HasColumnType("int");

                    b.Property<bool>("IsRefund")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PaymentMethodID")
                        .HasColumnType("int");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("ProcessedByEmployeeID")
                        .HasColumnType("int");

                    b.Property<string>("StripeTransactionID")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("PaymentID");

                    b.HasIndex("InvoiceID");

                    b.HasIndex("PaymentMethodID");

                    b.HasIndex("ProcessedByEmployeeID");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("SiteReservationSystem.Web.Models.PaymentMethod", b =>
                {
                    b.Property<int>("PaymentMethodID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentMethodID"));

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("MethodName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("RequiresOnlineProcessing")
                        .HasColumnType("bit");

                    b.HasKey("PaymentMethodID");

                    b.ToTable("PaymentMethods");

                    b.HasData(
                        new
                        {
                            PaymentMethodID = 1,
                            IsActive = true,
                            MethodName = "Credit Card",
                            RequiresOnlineProcessing = true
                        },
                        new
                        {
                            PaymentMethodID = 2,
                            IsActive = true,
                            MethodName = "Debit Card",
                            RequiresOnlineProcessing = true
                        },
                        new
                        {
                            PaymentMethodID = 3,
                            IsActive = true,
                            MethodName = "Cash",
                            RequiresOnlineProcessing = false
                        },
                        new
                        {
                            PaymentMethodID = 4,
                            IsActive = true,
                            MethodName = "Check",
                            RequiresOnlineProcessing = false
                        });
                });

            modelBuilder.Entity("SiteReservationSystem.Web.Models.Reservation", b =>
                {
                    b.Property<int>("ReservationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReservationID"));

                    b.Property<DateTime?>("ActualCheckInTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ActualCheckOutTime")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("BalanceDue")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("BaseAmount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("CustomerID")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("ReservationStatusID")
                        .HasColumnType("int");

                    b.Property<DateTime>("ScheduledCheckInTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ScheduledCheckOutTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("SiteID")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int?>("TrailerLengthFeet")
                        .HasColumnType("int");

                    b.HasKey("ReservationID");

                    b.HasIndex("CustomerID");

                    b.HasIndex("ReservationStatusID");

                    b.HasIndex("SiteID");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("SiteReservationSystem.Web.Models.ReservationFee", b =>
                {
                    b.Property<int>("ReservationFeeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReservationFeeID"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("DateApplied")
                        .HasColumnType("datetime2");

                    b.Property<int>("FeeID")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("ReservationID")
                        .HasColumnType("int");

                    b.HasKey("ReservationFeeID");

                    b.HasIndex("FeeID");

                    b.HasIndex("ReservationID");

                    b.ToTable("ReservationFees");
                });

            modelBuilder.Entity("SiteReservationSystem.Web.Models.ReservationStatus", b =>
                {
                    b.Property<int>("ReservationStatusID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReservationStatusID"));

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ReservationStatusID");

                    b.ToTable("ReservationStatuses");

                    b.HasData(
                        new
                        {
                            ReservationStatusID = 1,
                            Description = "Reservation is scheduled for future dates",
                            StatusName = "Upcoming"
                        },
                        new
                        {
                            ReservationStatusID = 2,
                            Description = "Guest is currently checked in",
                            StatusName = "In Progress"
                        },
                        new
                        {
                            ReservationStatusID = 3,
                            Description = "Reservation has been completed",
                            StatusName = "Completed"
                        },
                        new
                        {
                            ReservationStatusID = 4,
                            Description = "Reservation was cancelled",
                            StatusName = "Cancelled"
                        });
                });

            modelBuilder.Entity("SiteReservationSystem.Web.Models.Site", b =>
                {
                    b.Property<int>("SiteID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SiteID"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("MaxLengthFeet")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("SiteNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("SiteTypeID")
                        .HasColumnType("int");

                    b.HasKey("SiteID");

                    b.HasIndex("SiteNumber")
                        .IsUnique();

                    b.HasIndex("SiteTypeID");

                    b.ToTable("Sites");
                });

            modelBuilder.Entity("SiteReservationSystem.Web.Models.SitePhoto", b =>
                {
                    b.Property<int>("PhotoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PhotoID"));

                    b.Property<string>("Caption")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("DateUploaded")
                        .HasColumnType("datetime2");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("PhotoURL")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("SiteID")
                        .HasColumnType("int");

                    b.HasKey("PhotoID");

                    b.HasIndex("SiteID");

                    b.ToTable("SitePhotos");
                });

            modelBuilder.Entity("SiteReservationSystem.Web.Models.SiteType", b =>
                {
                    b.Property<int>("SiteTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SiteTypeID"));

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("SiteTypeID");

                    b.ToTable("SiteTypes");
                });

            modelBuilder.Entity("SiteReservationSystem.Web.Models.SiteTypePricing", b =>
                {
                    b.Property<int>("PricingID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PricingID"));

                    b.Property<decimal>("BasePrice")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("SiteTypeID")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("PricingID");

                    b.HasIndex("SiteTypeID");

                    b.ToTable("SiteTypePricings");
                });

            modelBuilder.Entity("SiteReservationSystem.Web.Models.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserID"));

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("UserID");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SiteReservationSystem.Web.Models.Admin", b =>
                {
                    b.HasOne("SiteReservationSystem.Web.Models.User", "User")
                        .WithOne("Admin")
                        .HasForeignKey("SiteReservationSystem.Web.Models.Admin", "UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SiteReservationSystem.Web.Models.Customer", b =>
                {
                    b.HasOne("SiteReservationSystem.Web.Models.User", "User")
                        .WithOne("Customer")
                        .HasForeignKey("SiteReservationSystem.Web.Models.Customer", "UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SiteReservationSystem.Web.Models.Employee", b =>
                {
                    b.HasOne("SiteReservationSystem.Web.Models.User", "User")
                        .WithOne("Employee")
                        .HasForeignKey("SiteReservationSystem.Web.Models.Employee", "UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SiteReservationSystem.Web.Models.Invoice", b =>
                {
                    b.HasOne("SiteReservationSystem.Web.Models.Customer", "Customer")
                        .WithMany("Invoices")
                        .HasForeignKey("CustomerID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SiteReservationSystem.Web.Models.Reservation", "Reservation")
                        .WithOne("Invoice")
                        .HasForeignKey("SiteReservationSystem.Web.Models.Invoice", "ReservationID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Reservation");
                });

            modelBuilder.Entity("SiteReservationSystem.Web.Models.Payment", b =>
                {
                    b.HasOne("SiteReservationSystem.Web.Models.Invoice", "Invoice")
                        .WithMany("Payments")
                        .HasForeignKey("InvoiceID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SiteReservationSystem.Web.Models.PaymentMethod", "PaymentMethod")
                        .WithMany("Payments")
                        .HasForeignKey("PaymentMethodID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SiteReservationSystem.Web.Models.Employee", "ProcessedByEmployee")
                        .WithMany("ProcessedPayments")
                        .HasForeignKey("ProcessedByEmployeeID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Invoice");

                    b.Navigation("PaymentMethod");

                    b.Navigation("ProcessedByEmployee");
                });

            modelBuilder.Entity("SiteReservationSystem.Web.Models.Reservation", b =>
                {
                    b.HasOne("SiteReservationSystem.Web.Models.Customer", "Customer")
                        .WithMany("Reservations")
                        .HasForeignKey("CustomerID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SiteReservationSystem.Web.Models.ReservationStatus", "ReservationStatus")
                        .WithMany("Reservations")
                        .HasForeignKey("ReservationStatusID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SiteReservationSystem.Web.Models.Site", "Site")
                        .WithMany("Reservations")
                        .HasForeignKey("SiteID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("ReservationStatus");

                    b.Navigation("Site");
                });

            modelBuilder.Entity("SiteReservationSystem.Web.Models.ReservationFee", b =>
                {
                    b.HasOne("SiteReservationSystem.Web.Models.Fee", "Fee")
                        .WithMany("ReservationFees")
                        .HasForeignKey("FeeID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SiteReservationSystem.Web.Models.Reservation", "Reservation")
                        .WithMany("ReservationFees")
                        .HasForeignKey("ReservationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fee");

                    b.Navigation("Reservation");
                });

            modelBuilder.Entity("SiteReservationSystem.Web.Models.Site", b =>
                {
                    b.HasOne("SiteReservationSystem.Web.Models.SiteType", "SiteType")
                        .WithMany("Sites")
                        .HasForeignKey("SiteTypeID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SiteType");
                });

            modelBuilder.Entity("SiteReservationSystem.Web.Models.SitePhoto", b =>
                {
                    b.HasOne("SiteReservationSystem.Web.Models.Site", "Site")
                        .WithMany("SitePhotos")
                        .HasForeignKey("SiteID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Site");
                });

            modelBuilder.Entity("SiteReservationSystem.Web.Models.SiteTypePricing", b =>
                {
                    b.HasOne("SiteReservationSystem.Web.Models.SiteType", "SiteType")
                        .WithMany("SiteTypePricings")
                        .HasForeignKey("SiteTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SiteType");
                });

            modelBuilder.Entity("SiteReservationSystem.Web.Models.Customer", b =>
                {
                    b.Navigation("Invoices");

                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("SiteReservationSystem.Web.Models.Employee", b =>
                {
                    b.Navigation("ProcessedPayments");
                });

            modelBuilder.Entity("SiteReservationSystem.Web.Models.Fee", b =>
                {
                    b.Navigation("ReservationFees");
                });

            modelBuilder.Entity("SiteReservationSystem.Web.Models.Invoice", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("SiteReservationSystem.Web.Models.PaymentMethod", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("SiteReservationSystem.Web.Models.Reservation", b =>
                {
                    b.Navigation("Invoice");

                    b.Navigation("ReservationFees");
                });

            modelBuilder.Entity("SiteReservationSystem.Web.Models.ReservationStatus", b =>
                {
                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("SiteReservationSystem.Web.Models.Site", b =>
                {
                    b.Navigation("Reservations");

                    b.Navigation("SitePhotos");
                });

            modelBuilder.Entity("SiteReservationSystem.Web.Models.SiteType", b =>
                {
                    b.Navigation("SiteTypePricings");

                    b.Navigation("Sites");
                });

            modelBuilder.Entity("SiteReservationSystem.Web.Models.User", b =>
                {
                    b.Navigation("Admin");

                    b.Navigation("Customer");

                    b.Navigation("Employee");
                });
#pragma warning restore 612, 618
        }
    }
}
