// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SiteReservationSystem.Web.Data;

#nullable disable

namespace SiteReservationSystem.Web.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SiteReservationSystem.Web.Models.Admin", b =>
                {
                    b.Property<int>("AdminID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AdminID"));

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("AdminID");

                    b.HasIndex("UserID")
                        .IsUnique();

                    b.ToTable("Admins");

                    b.HasData(
                        new
                        {
                            AdminID = 1,
                            DateCreated = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Demo",
                            LastName = "Admin",
                            UserID = 1
                        });
                });

            modelBuilder.Entity("SiteReservationSystem.Web.Models.Customer", b =>
                {
                    b.Property<int>("CustomerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerID"));

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<int>("DoDStatus")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("MilitaryAffiliation")
                        .HasColumnType("int");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("CustomerID");

                    b.HasIndex("UserID")
                        .IsUnique();

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            CustomerID = 1,
                            DateCreated = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DoDStatus = 0,
                            FirstName = "John",
                            LastName = "Smith",
                            MilitaryAffiliation = 0,
                            PhoneNumber = "555-123-4567",
                            UserID = 3
                        });
                });

            modelBuilder.Entity("SiteReservationSystem.Web.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeID"));

                    b.Property<int>("AccessPermissions")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateHired")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsLockedOut")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("EmployeeID");

                    b.HasIndex("UserID")
                        .IsUnique();

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            EmployeeID = 1,
                            AccessPermissions = 24,
                            DateHired = new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Jane",
                            IsActive = true,
                            IsLockedOut = false,
                            LastName = "Doe",
                            UserID = 2
                        });
                });

            modelBuilder.Entity("SiteReservationSystem.Web.Models.Fee", b =>
                {
                    b.Property<int>("FeeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FeeID"));

                    b.Property<decimal>("DefaultAmount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FeeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("FeeID");

                    b.ToTable("Fees");

                    b.HasData(
                        new
                        {
                            FeeID = 1,
                            DefaultAmount = 25.00m,
                            Description = "Fee for checking out after designated time",
                            FeeName = "Late Checkout",
                            IsActive = true
                        },
                        new
                        {
                            FeeID = 2,
                            DefaultAmount = 15.00m,
                            Description = "Fee for checking in before standard time",
                            FeeName = "Early Check-in",
                            IsActive = true
                        },
                        new
                        {
                            FeeID = 3,
                            DefaultAmount = 10.00m,
                            Description = "Standard cancellation fee",
                            FeeName = "Cancellation Fee",
                            IsActive = true
                        });
                });

            modelBuilder.Entity("SiteReservationSystem.Web.Models.Invoice", b =>
                {
                    b.Property<int>("InvoiceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InvoiceID"));

                    b.Property<int>("CustomerID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DatePaid")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("InvoiceDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("ReservationID")
                        .HasColumnType("int");

                    b.Property<decimal>("SubTotal")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("TotalFees")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("InvoiceID");

                    b.HasIndex("CustomerID");

                    b.HasIndex("ReservationID")
                        .IsUnique();

                    b.ToTable("Invoices");

                    b.HasData(
                        new
                        {
                            InvoiceID = 1,
                            CustomerID = 1,
                            DatePaid = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DueDate = new DateTime(2026, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InvoiceDate = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPaid = true,
                            ReservationID = 1,
                            SubTotal = 75.00m,
                            TotalAmount = 75.00m,
                            TotalFees = 0m
                        },
                        new
                        {
                            InvoiceID = 2,
                            CustomerID = 1,
                            DatePaid = new DateTime(2026, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DueDate = new DateTime(2026, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InvoiceDate = new DateTime(2026, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPaid = true,
                            ReservationID = 2,
                            SubTotal = 100.00m,
                            TotalAmount = 110.00m,
                            TotalFees = 10.00m
                        },
                        new
                        {
                            InvoiceID = 3,
                            CustomerID = 1,
                            DatePaid = new DateTime(2026, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DueDate = new DateTime(2026, 4, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InvoiceDate = new DateTime(2026, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPaid = true,
                            ReservationID = 3,
                            SubTotal = 175.00m,
                            TotalAmount = 175.00m,
                            TotalFees = 0m
                        },
                        new
                        {
                            InvoiceID = 4,
                            CustomerID = 1,
                            DatePaid = new DateTime(2026, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DueDate = new DateTime(2026, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InvoiceDate = new DateTime(2026, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPaid = true,
                            ReservationID = 4,
                            SubTotal = 90.00m,
                            TotalAmount = 90.00m,
                            TotalFees = 0m
                        },
                        new
                        {
                            InvoiceID = 5,
                            CustomerID = 1,
                            DatePaid = new DateTime(2026, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DueDate = new DateTime(2026, 4, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InvoiceDate = new DateTime(2026, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPaid = true,
                            ReservationID = 5,
                            SubTotal = 150.00m,
                            TotalAmount = 165.00m,
                            TotalFees = 15.00m
                        },
                        new
                        {
                            InvoiceID = 6,
                            CustomerID = 1,
                            DatePaid = new DateTime(2026, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DueDate = new DateTime(2026, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InvoiceDate = new DateTime(2026, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPaid = true,
                            ReservationID = 6,
                            SubTotal = 120.00m,
                            TotalAmount = 120.00m,
                            TotalFees = 0m
                        },
                        new
                        {
                            InvoiceID = 7,
                            CustomerID = 1,
                            DatePaid = new DateTime(2026, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DueDate = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InvoiceDate = new DateTime(2026, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPaid = true,
                            ReservationID = 7,
                            SubTotal = 50.00m,
                            TotalAmount = 50.00m,
                            TotalFees = 0m
                        },
                        new
                        {
                            InvoiceID = 8,
                            CustomerID = 1,
                            DatePaid = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DueDate = new DateTime(2026, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InvoiceDate = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPaid = true,
                            ReservationID = 8,
                            SubTotal = 30.00m,
                            TotalAmount = 40.00m,
                            TotalFees = 10.00m
                        },
                        new
                        {
                            InvoiceID = 9,
                            CustomerID = 1,
                            DatePaid = new DateTime(2026, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DueDate = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InvoiceDate = new DateTime(2026, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPaid = true,
                            ReservationID = 9,
                            SubTotal = 150.00m,
                            TotalAmount = 150.00m,
                            TotalFees = 0m
                        },
                        new
                        {
                            InvoiceID = 10,
                            CustomerID = 1,
                            DatePaid = new DateTime(2026, 2, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DueDate = new DateTime(2026, 2, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InvoiceDate = new DateTime(2026, 2, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPaid = true,
                            ReservationID = 10,
                            SubTotal = 34.00m,
                            TotalAmount = 34.00m,
                            TotalFees = 0m
                        },
                        new
                        {
                            InvoiceID = 11,
                            CustomerID = 1,
                            DatePaid = new DateTime(2026, 4, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DueDate = new DateTime(2026, 4, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InvoiceDate = new DateTime(2026, 4, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPaid = true,
                            ReservationID = 11,
                            SubTotal = 51.00m,
                            TotalAmount = 76.00m,
                            TotalFees = 25.00m
                        },
                        new
                        {
                            InvoiceID = 12,
                            CustomerID = 1,
                            DatePaid = new DateTime(2026, 4, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DueDate = new DateTime(2026, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InvoiceDate = new DateTime(2026, 4, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPaid = true,
                            ReservationID = 12,
                            SubTotal = 68.00m,
                            TotalAmount = 68.00m,
                            TotalFees = 0m
                        });
                });

            modelBuilder.Entity("SiteReservationSystem.Web.Models.Payment", b =>
                {
                    b.Property<int>("PaymentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentID"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("InvoiceID")
                        .HasColumnType("int");

                    b.Property<bool>("IsRefund")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PaymentMethodID")
                        .HasColumnType("int");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("ProcessedByEmployeeID")
                        .HasColumnType("int");

                    b.Property<string>("StripeTransactionID")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("PaymentID");

                    b.HasIndex("InvoiceID");

                    b.HasIndex("PaymentMethodID");

                    b.HasIndex("ProcessedByEmployeeID");

                    b.ToTable("Payments");

                    b.HasData(
                        new
                        {
                            PaymentID = 1,
                            Amount = 75.00m,
                            InvoiceID = 1,
                            IsRefund = false,
                            PaymentDate = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PaymentMethodID = 1,
                            PaymentStatus = "Completed",
                            StripeTransactionID = "txn_demo_001"
                        },
                        new
                        {
                            PaymentID = 2,
                            Amount = 110.00m,
                            InvoiceID = 2,
                            IsRefund = false,
                            PaymentDate = new DateTime(2026, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PaymentMethodID = 1,
                            PaymentStatus = "Completed",
                            StripeTransactionID = "txn_demo_002"
                        },
                        new
                        {
                            PaymentID = 3,
                            Amount = -100.00m,
                            InvoiceID = 2,
                            IsRefund = true,
                            Notes = "Refund: $100.00 (kept $10.00 cancellation fee)",
                            PaymentDate = new DateTime(2026, 2, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PaymentMethodID = 1,
                            PaymentStatus = "Refunded",
                            StripeTransactionID = "txn_demo_002_refund"
                        },
                        new
                        {
                            PaymentID = 4,
                            Amount = 175.00m,
                            InvoiceID = 3,
                            IsRefund = false,
                            PaymentDate = new DateTime(2026, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PaymentMethodID = 2,
                            PaymentStatus = "Completed",
                            StripeTransactionID = "txn_demo_003"
                        },
                        new
                        {
                            PaymentID = 5,
                            Amount = 90.00m,
                            InvoiceID = 4,
                            IsRefund = false,
                            PaymentDate = new DateTime(2026, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PaymentMethodID = 1,
                            PaymentStatus = "Completed",
                            StripeTransactionID = "txn_demo_004"
                        },
                        new
                        {
                            PaymentID = 6,
                            Amount = 165.00m,
                            InvoiceID = 5,
                            IsRefund = false,
                            PaymentDate = new DateTime(2026, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PaymentMethodID = 1,
                            PaymentStatus = "Completed",
                            StripeTransactionID = "txn_demo_005"
                        },
                        new
                        {
                            PaymentID = 7,
                            Amount = 120.00m,
                            InvoiceID = 6,
                            IsRefund = false,
                            PaymentDate = new DateTime(2026, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PaymentMethodID = 2,
                            PaymentStatus = "Completed",
                            StripeTransactionID = "txn_demo_006"
                        },
                        new
                        {
                            PaymentID = 8,
                            Amount = 50.00m,
                            InvoiceID = 7,
                            IsRefund = false,
                            PaymentDate = new DateTime(2026, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PaymentMethodID = 3,
                            PaymentStatus = "Completed",
                            ProcessedByEmployeeID = 1
                        },
                        new
                        {
                            PaymentID = 9,
                            Amount = 40.00m,
                            InvoiceID = 8,
                            IsRefund = false,
                            PaymentDate = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PaymentMethodID = 1,
                            PaymentStatus = "Completed",
                            StripeTransactionID = "txn_demo_008"
                        },
                        new
                        {
                            PaymentID = 10,
                            Amount = -30.00m,
                            InvoiceID = 8,
                            IsRefund = true,
                            Notes = "Refund: $30.00 (kept $10.00 cancellation fee)",
                            PaymentDate = new DateTime(2026, 3, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PaymentMethodID = 1,
                            PaymentStatus = "Refunded",
                            StripeTransactionID = "txn_demo_008_refund"
                        },
                        new
                        {
                            PaymentID = 11,
                            Amount = 150.00m,
                            InvoiceID = 9,
                            IsRefund = false,
                            PaymentDate = new DateTime(2026, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PaymentMethodID = 3,
                            PaymentStatus = "Completed",
                            ProcessedByEmployeeID = 1
                        },
                        new
                        {
                            PaymentID = 12,
                            Amount = 34.00m,
                            InvoiceID = 10,
                            IsRefund = false,
                            PaymentDate = new DateTime(2026, 2, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PaymentMethodID = 2,
                            PaymentStatus = "Completed",
                            StripeTransactionID = "txn_demo_010"
                        },
                        new
                        {
                            PaymentID = 13,
                            Amount = 76.00m,
                            InvoiceID = 11,
                            IsRefund = false,
                            PaymentDate = new DateTime(2026, 4, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PaymentMethodID = 1,
                            PaymentStatus = "Completed",
                            StripeTransactionID = "txn_demo_011"
                        },
                        new
                        {
                            PaymentID = 14,
                            Amount = 68.00m,
                            InvoiceID = 12,
                            IsRefund = false,
                            PaymentDate = new DateTime(2026, 4, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PaymentMethodID = 1,
                            PaymentStatus = "Completed",
                            StripeTransactionID = "txn_demo_012"
                        });
                });

            modelBuilder.Entity("SiteReservationSystem.Web.Models.PaymentMethod", b =>
                {
                    b.Property<int>("PaymentMethodID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentMethodID"));

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("MethodName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("RequiresOnlineProcessing")
                        .HasColumnType("bit");

                    b.HasKey("PaymentMethodID");

                    b.ToTable("PaymentMethods");

                    b.HasData(
                        new
                        {
                            PaymentMethodID = 1,
                            IsActive = true,
                            MethodName = "Credit Card",
                            RequiresOnlineProcessing = true
                        },
                        new
                        {
                            PaymentMethodID = 2,
                            IsActive = true,
                            MethodName = "Debit Card",
                            RequiresOnlineProcessing = true
                        },
                        new
                        {
                            PaymentMethodID = 3,
                            IsActive = true,
                            MethodName = "Cash",
                            RequiresOnlineProcessing = false
                        },
                        new
                        {
                            PaymentMethodID = 4,
                            IsActive = true,
                            MethodName = "Check",
                            RequiresOnlineProcessing = false
                        });
                });

            modelBuilder.Entity("SiteReservationSystem.Web.Models.Reservation", b =>
                {
                    b.Property<int>("ReservationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReservationID"));

                    b.Property<DateTime?>("ActualCheckInTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ActualCheckOutTime")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("BalanceDue")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("BaseAmount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("CustomerID")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("NumberOfGuests")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfPets")
                        .HasColumnType("int");

                    b.Property<int>("ReservationStatusID")
                        .HasColumnType("int");

                    b.Property<DateTime>("ScheduledCheckInTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ScheduledCheckOutTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("SiteID")
                        .HasColumnType("int");

                    b.Property<string>("SpecialRequests")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int?>("TrailerLengthFeet")
                        .HasColumnType("int");

                    b.HasKey("ReservationID");

                    b.HasIndex("CustomerID");

                    b.HasIndex("ReservationStatusID");

                    b.HasIndex("SiteID");

                    b.ToTable("Reservations");

                    b.HasData(
                        new
                        {
                            ReservationID = 1,
                            ActualCheckInTime = new DateTime(2026, 2, 10, 13, 20, 0, 0, DateTimeKind.Unspecified),
                            ActualCheckOutTime = new DateTime(2026, 2, 13, 11, 50, 0, 0, DateTimeKind.Unspecified),
                            BalanceDue = 0m,
                            BaseAmount = 75.00m,
                            CustomerID = 1,
                            DateCreated = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDate = new DateTime(2026, 2, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastUpdated = new DateTime(2026, 2, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NumberOfGuests = 0,
                            NumberOfPets = 0,
                            ReservationStatusID = 3,
                            ScheduledCheckInTime = new DateTime(2026, 2, 10, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            ScheduledCheckOutTime = new DateTime(2026, 2, 13, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            SiteID = 1,
                            StartDate = new DateTime(2026, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalAmount = 75.00m,
                            TrailerLengthFeet = 38
                        },
                        new
                        {
                            ReservationID = 2,
                            BalanceDue = 0m,
                            BaseAmount = 100.00m,
                            CustomerID = 1,
                            DateCreated = new DateTime(2026, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDate = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastUpdated = new DateTime(2026, 2, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Cancelled - plans changed",
                            NumberOfGuests = 0,
                            NumberOfPets = 0,
                            ReservationStatusID = 4,
                            ScheduledCheckInTime = new DateTime(2026, 3, 5, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            ScheduledCheckOutTime = new DateTime(2026, 3, 9, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            SiteID = 2,
                            StartDate = new DateTime(2026, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalAmount = 110.00m,
                            TrailerLengthFeet = 42
                        },
                        new
                        {
                            ReservationID = 3,
                            BalanceDue = 0m,
                            BaseAmount = 175.00m,
                            CustomerID = 1,
                            DateCreated = new DateTime(2026, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDate = new DateTime(2026, 5, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastUpdated = new DateTime(2026, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NumberOfGuests = 0,
                            NumberOfPets = 0,
                            ReservationStatusID = 1,
                            ScheduledCheckInTime = new DateTime(2026, 4, 25, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            ScheduledCheckOutTime = new DateTime(2026, 5, 2, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            SiteID = 3,
                            StartDate = new DateTime(2026, 4, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalAmount = 175.00m,
                            TrailerLengthFeet = 60
                        },
                        new
                        {
                            ReservationID = 4,
                            ActualCheckInTime = new DateTime(2026, 2, 20, 13, 10, 0, 0, DateTimeKind.Unspecified),
                            ActualCheckOutTime = new DateTime(2026, 2, 23, 11, 30, 0, 0, DateTimeKind.Unspecified),
                            BalanceDue = 0m,
                            BaseAmount = 90.00m,
                            CustomerID = 1,
                            DateCreated = new DateTime(2026, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDate = new DateTime(2026, 2, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastUpdated = new DateTime(2026, 2, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NumberOfGuests = 0,
                            NumberOfPets = 0,
                            ReservationStatusID = 3,
                            ScheduledCheckInTime = new DateTime(2026, 2, 20, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            ScheduledCheckOutTime = new DateTime(2026, 2, 23, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            SiteID = 4,
                            StartDate = new DateTime(2026, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalAmount = 90.00m
                        },
                        new
                        {
                            ReservationID = 5,
                            ActualCheckInTime = new DateTime(2026, 4, 18, 8, 10, 0, 0, DateTimeKind.Unspecified),
                            BalanceDue = 0m,
                            BaseAmount = 150.00m,
                            CustomerID = 1,
                            DateCreated = new DateTime(2026, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDate = new DateTime(2026, 4, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastUpdated = new DateTime(2026, 4, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NumberOfGuests = 0,
                            NumberOfPets = 0,
                            ReservationStatusID = 2,
                            ScheduledCheckInTime = new DateTime(2026, 4, 18, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            ScheduledCheckOutTime = new DateTime(2026, 4, 23, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            SiteID = 5,
                            StartDate = new DateTime(2026, 4, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalAmount = 165.00m
                        },
                        new
                        {
                            ReservationID = 6,
                            BalanceDue = 0m,
                            BaseAmount = 120.00m,
                            CustomerID = 1,
                            DateCreated = new DateTime(2026, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDate = new DateTime(2026, 5, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastUpdated = new DateTime(2026, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NumberOfGuests = 0,
                            NumberOfPets = 0,
                            ReservationStatusID = 1,
                            ScheduledCheckInTime = new DateTime(2026, 5, 10, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            ScheduledCheckOutTime = new DateTime(2026, 5, 14, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            SiteID = 4,
                            StartDate = new DateTime(2026, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalAmount = 120.00m
                        },
                        new
                        {
                            ReservationID = 7,
                            ActualCheckInTime = new DateTime(2026, 2, 1, 13, 30, 0, 0, DateTimeKind.Unspecified),
                            ActualCheckOutTime = new DateTime(2026, 2, 11, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            BalanceDue = 0m,
                            BaseAmount = 50.00m,
                            CustomerID = 1,
                            DateCreated = new DateTime(2026, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDate = new DateTime(2026, 2, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastUpdated = new DateTime(2026, 2, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NumberOfGuests = 0,
                            NumberOfPets = 0,
                            ReservationStatusID = 3,
                            ScheduledCheckInTime = new DateTime(2026, 2, 1, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            ScheduledCheckOutTime = new DateTime(2026, 2, 11, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            SiteID = 6,
                            StartDate = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalAmount = 50.00m,
                            TrailerLengthFeet = 45
                        },
                        new
                        {
                            ReservationID = 8,
                            BalanceDue = 0m,
                            BaseAmount = 30.00m,
                            CustomerID = 1,
                            DateCreated = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDate = new DateTime(2026, 3, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastUpdated = new DateTime(2026, 3, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Cancelled - vehicle sold",
                            NumberOfGuests = 0,
                            NumberOfPets = 0,
                            ReservationStatusID = 4,
                            ScheduledCheckInTime = new DateTime(2026, 3, 15, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            ScheduledCheckOutTime = new DateTime(2026, 3, 21, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            SiteID = 7,
                            StartDate = new DateTime(2026, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalAmount = 40.00m,
                            TrailerLengthFeet = 50
                        },
                        new
                        {
                            ReservationID = 9,
                            BalanceDue = 0m,
                            BaseAmount = 150.00m,
                            CustomerID = 1,
                            DateCreated = new DateTime(2026, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDate = new DateTime(2026, 5, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastUpdated = new DateTime(2026, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "30-day dry storage rental",
                            NumberOfGuests = 0,
                            NumberOfPets = 0,
                            ReservationStatusID = 1,
                            ScheduledCheckInTime = new DateTime(2026, 5, 1, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            ScheduledCheckOutTime = new DateTime(2026, 5, 31, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            SiteID = 6,
                            StartDate = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalAmount = 150.00m,
                            TrailerLengthFeet = 48
                        },
                        new
                        {
                            ReservationID = 10,
                            ActualCheckInTime = new DateTime(2026, 2, 28, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            ActualCheckOutTime = new DateTime(2026, 3, 2, 11, 45, 0, 0, DateTimeKind.Unspecified),
                            BalanceDue = 0m,
                            BaseAmount = 34.00m,
                            CustomerID = 1,
                            DateCreated = new DateTime(2026, 2, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDate = new DateTime(2026, 3, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastUpdated = new DateTime(2026, 3, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NumberOfGuests = 0,
                            NumberOfPets = 0,
                            ReservationStatusID = 3,
                            ScheduledCheckInTime = new DateTime(2026, 2, 28, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            ScheduledCheckOutTime = new DateTime(2026, 3, 2, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            SiteID = 8,
                            StartDate = new DateTime(2026, 2, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalAmount = 34.00m
                        },
                        new
                        {
                            ReservationID = 11,
                            ActualCheckInTime = new DateTime(2026, 4, 17, 13, 5, 0, 0, DateTimeKind.Unspecified),
                            BalanceDue = 0m,
                            BaseAmount = 51.00m,
                            CustomerID = 1,
                            DateCreated = new DateTime(2026, 4, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDate = new DateTime(2026, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastUpdated = new DateTime(2026, 4, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NumberOfGuests = 0,
                            NumberOfPets = 0,
                            ReservationStatusID = 2,
                            ScheduledCheckInTime = new DateTime(2026, 4, 17, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            ScheduledCheckOutTime = new DateTime(2026, 4, 20, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            SiteID = 8,
                            StartDate = new DateTime(2026, 4, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalAmount = 76.00m
                        },
                        new
                        {
                            ReservationID = 12,
                            BalanceDue = 0m,
                            BaseAmount = 68.00m,
                            CustomerID = 1,
                            DateCreated = new DateTime(2026, 4, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndDate = new DateTime(2026, 5, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastUpdated = new DateTime(2026, 4, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NumberOfGuests = 0,
                            NumberOfPets = 0,
                            ReservationStatusID = 1,
                            ScheduledCheckInTime = new DateTime(2026, 5, 5, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            ScheduledCheckOutTime = new DateTime(2026, 5, 9, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            SiteID = 8,
                            StartDate = new DateTime(2026, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalAmount = 68.00m
                        });
                });

            modelBuilder.Entity("SiteReservationSystem.Web.Models.ReservationFee", b =>
                {
                    b.Property<int>("ReservationFeeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReservationFeeID"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("DateApplied")
                        .HasColumnType("datetime2");

                    b.Property<int>("FeeID")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("ReservationID")
                        .HasColumnType("int");

                    b.HasKey("ReservationFeeID");

                    b.HasIndex("FeeID");

                    b.HasIndex("ReservationID");

                    b.ToTable("ReservationFees");

                    b.HasData(
                        new
                        {
                            ReservationFeeID = 1,
                            Amount = 10.00m,
                            DateApplied = new DateTime(2026, 2, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FeeID = 3,
                            Notes = "Cancellation fee applied",
                            ReservationID = 2
                        },
                        new
                        {
                            ReservationFeeID = 2,
                            Amount = 15.00m,
                            DateApplied = new DateTime(2026, 4, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FeeID = 2,
                            Notes = "Early check-in at 8:00 AM",
                            ReservationID = 5
                        },
                        new
                        {
                            ReservationFeeID = 3,
                            Amount = 10.00m,
                            DateApplied = new DateTime(2026, 3, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FeeID = 3,
                            Notes = "Cancellation fee applied",
                            ReservationID = 8
                        },
                        new
                        {
                            ReservationFeeID = 4,
                            Amount = 25.00m,
                            DateApplied = new DateTime(2026, 4, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FeeID = 1,
                            Notes = "Late checkout requested",
                            ReservationID = 11
                        });
                });

            modelBuilder.Entity("SiteReservationSystem.Web.Models.ReservationStatus", b =>
                {
                    b.Property<int>("ReservationStatusID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReservationStatusID"));

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ReservationStatusID");

                    b.ToTable("ReservationStatuses");

                    b.HasData(
                        new
                        {
                            ReservationStatusID = 1,
                            Description = "Reservation is scheduled for future dates",
                            StatusName = "Upcoming"
                        },
                        new
                        {
                            ReservationStatusID = 2,
                            Description = "Guest is currently checked in",
                            StatusName = "In Progress"
                        },
                        new
                        {
                            ReservationStatusID = 3,
                            Description = "Reservation has been completed",
                            StatusName = "Completed"
                        },
                        new
                        {
                            ReservationStatusID = 4,
                            Description = "Reservation was cancelled",
                            StatusName = "Cancelled"
                        });
                });

            modelBuilder.Entity("SiteReservationSystem.Web.Models.Site", b =>
                {
                    b.Property<int>("SiteID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SiteID"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("MaxLengthFeet")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("SiteNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("SiteTypeID")
                        .HasColumnType("int");

                    b.HasKey("SiteID");

                    b.HasIndex("SiteNumber")
                        .IsUnique();

                    b.HasIndex("SiteTypeID");

                    b.ToTable("Sites");

                    b.HasData(
                        new
                        {
                            SiteID = 1,
                            IsActive = true,
                            MaxLengthFeet = 40,
                            SiteNumber = "2",
                            SiteTypeID = 1
                        },
                        new
                        {
                            SiteID = 2,
                            IsActive = true,
                            MaxLengthFeet = 45,
                            SiteNumber = "17",
                            SiteTypeID = 1
                        },
                        new
                        {
                            SiteID = 3,
                            IsActive = true,
                            MaxLengthFeet = 65,
                            SiteNumber = "32",
                            SiteTypeID = 1
                        },
                        new
                        {
                            SiteID = 4,
                            IsActive = true,
                            MaxLengthFeet = 30,
                            Notes = "Walk-in trailer with linens",
                            SiteNumber = "11B",
                            SiteTypeID = 2
                        },
                        new
                        {
                            SiteID = 5,
                            IsActive = true,
                            MaxLengthFeet = 30,
                            Notes = "Walk-in trailer with linens",
                            SiteNumber = "12B",
                            SiteTypeID = 2
                        },
                        new
                        {
                            SiteID = 6,
                            IsActive = true,
                            MaxLengthFeet = 65,
                            Notes = "Dry storage site",
                            SiteNumber = "A",
                            SiteTypeID = 3
                        },
                        new
                        {
                            SiteID = 7,
                            IsActive = true,
                            MaxLengthFeet = 65,
                            Notes = "Dry storage site",
                            SiteNumber = "B",
                            SiteTypeID = 3
                        },
                        new
                        {
                            SiteID = 8,
                            IsActive = true,
                            MaxLengthFeet = 0,
                            Notes = "Tent site near Dog Park",
                            SiteNumber = "TENT-1",
                            SiteTypeID = 4
                        });
                });

            modelBuilder.Entity("SiteReservationSystem.Web.Models.SitePhoto", b =>
                {
                    b.Property<int>("PhotoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PhotoID"));

                    b.Property<string>("Caption")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("DateUploaded")
                        .HasColumnType("datetime2");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("PhotoURL")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("SiteID")
                        .HasColumnType("int");

                    b.HasKey("PhotoID");

                    b.HasIndex("SiteID");

                    b.ToTable("SitePhotos");

                    b.HasData(
                        new
                        {
                            PhotoID = 1,
                            Caption = "Site 2 - 40ft Trailer",
                            DateUploaded = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DisplayOrder = 1,
                            PhotoURL = "https://i0.wp.com/pointofrocksrvcampground.com/wp-content/uploads/2019/05/IMG_0694.jpg?w=4032&ssl=1",
                            SiteID = 1
                        },
                        new
                        {
                            PhotoID = 2,
                            Caption = "Site 17 - 45ft Trailer",
                            DateUploaded = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DisplayOrder = 1,
                            PhotoURL = "https://i0.wp.com/pointofrocksrvcampground.com/wp-content/uploads/2019/05/IMG_0954.jpg?w=4032&ssl=1",
                            SiteID = 2
                        },
                        new
                        {
                            PhotoID = 9,
                            Caption = "Site 17 - Hookup View",
                            DateUploaded = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DisplayOrder = 2,
                            PhotoURL = "https://i0.wp.com/pointofrocksrvcampground.com/wp-content/uploads/2019/05/IMG_0512.jpg?w=4032&ssl=1",
                            SiteID = 2
                        },
                        new
                        {
                            PhotoID = 3,
                            Caption = "Site 32 - 65ft Trailer",
                            DateUploaded = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DisplayOrder = 1,
                            PhotoURL = "https://i0.wp.com/pointofrocksrvcampground.com/wp-content/uploads/2019/06/IMG_1226.jpg?w=4032&ssl=1",
                            SiteID = 3
                        },
                        new
                        {
                            PhotoID = 4,
                            Caption = "Site 11B - Walk-in Trailer",
                            DateUploaded = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DisplayOrder = 1,
                            PhotoURL = "https://i0.wp.com/pointofrocksrvcampground.com/wp-content/uploads/2019/06/IMG_1309.jpg?w=4032&ssl=1",
                            SiteID = 4
                        },
                        new
                        {
                            PhotoID = 5,
                            Caption = "Site 12B - Walk-in Trailer",
                            DateUploaded = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DisplayOrder = 1,
                            PhotoURL = "https://i0.wp.com/pointofrocksrvcampground.com/wp-content/uploads/2019/05/IMG_0439.jpg?w=4032&ssl=1",
                            SiteID = 5
                        },
                        new
                        {
                            PhotoID = 6,
                            Caption = "Dry Storage A",
                            DateUploaded = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DisplayOrder = 1,
                            PhotoURL = "https://i0.wp.com/pointofrocksrvcampground.com/wp-content/uploads/2019/05/IMG_0603.jpg?w=4032&ssl=1",
                            SiteID = 6
                        },
                        new
                        {
                            PhotoID = 7,
                            Caption = "Dry Storage B",
                            DateUploaded = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DisplayOrder = 1,
                            PhotoURL = "https://i0.wp.com/pointofrocksrvcampground.com/wp-content/uploads/2019/05/IMG_0444.jpg?w=4032&ssl=1",
                            SiteID = 7
                        },
                        new
                        {
                            PhotoID = 8,
                            Caption = "Tent Site - Near Dog Park",
                            DateUploaded = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DisplayOrder = 1,
                            PhotoURL = "https://i0.wp.com/pointofrocksrvcampground.com/wp-content/uploads/2019/05/IMG_0515.jpg?w=4032&ssl=1",
                            SiteID = 8
                        });
                });

            modelBuilder.Entity("SiteReservationSystem.Web.Models.SiteType", b =>
                {
                    b.Property<int>("SiteTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SiteTypeID"));

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("SiteTypeID");

                    b.ToTable("SiteTypes");

                    b.HasData(
                        new
                        {
                            SiteTypeID = 1,
                            Description = "Standard trailer sites for vehicles 1-45 feet",
                            IsActive = true,
                            TypeName = "Trailers (1-45)"
                        },
                        new
                        {
                            SiteTypeID = 2,
                            Description = "Walk-in trailer sites with linens provided",
                            IsActive = true,
                            TypeName = "Walk-in Trailers (11B, 12B)"
                        },
                        new
                        {
                            SiteTypeID = 3,
                            Description = "Dry storage sites for RV parking",
                            IsActive = true,
                            TypeName = "Dry Storage"
                        },
                        new
                        {
                            SiteTypeID = 4,
                            Description = "Tent camping site near Dog Park",
                            IsActive = true,
                            TypeName = "Tent Site"
                        });
                });

            modelBuilder.Entity("SiteReservationSystem.Web.Models.SiteTypePricing", b =>
                {
                    b.Property<int>("PricingID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PricingID"));

                    b.Property<decimal>("BasePrice")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("SiteTypeID")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("PricingID");

                    b.HasIndex("SiteTypeID");

                    b.ToTable("SiteTypePricings");

                    b.HasData(
                        new
                        {
                            PricingID = 1,
                            BasePrice = 25.00m,
                            Description = "Current rate for standard trailers",
                            SiteTypeID = 1,
                            StartDate = new DateTime(2025, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PricingID = 2,
                            BasePrice = 30.00m,
                            Description = "Current rate for walk-in trailers",
                            SiteTypeID = 2,
                            StartDate = new DateTime(2025, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PricingID = 3,
                            BasePrice = 5.00m,
                            Description = "Current daily rate for dry storage",
                            SiteTypeID = 3,
                            StartDate = new DateTime(2025, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PricingID = 4,
                            BasePrice = 17.00m,
                            Description = "Current rate for tent site",
                            SiteTypeID = 4,
                            StartDate = new DateTime(2025, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("SiteReservationSystem.Web.Models.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserID"));

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("UserID");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserID = 1,
                            DateCreated = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "admin@rvpark.com",
                            IsActive = true,
                            PasswordHash = "Password123!",
                            Role = 2
                        },
                        new
                        {
                            UserID = 2,
                            DateCreated = new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "jane.doe@rvpark.com",
                            IsActive = true,
                            PasswordHash = "Password123!",
                            Role = 1
                        },
                        new
                        {
                            UserID = 3,
                            DateCreated = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "john.smith@military.com",
                            IsActive = true,
                            PasswordHash = "Password123!",
                            Role = 0
                        });
                });

            modelBuilder.Entity("SiteReservationSystem.Web.Models.Admin", b =>
                {
                    b.HasOne("SiteReservationSystem.Web.Models.User", "User")
                        .WithOne("Admin")
                        .HasForeignKey("SiteReservationSystem.Web.Models.Admin", "UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SiteReservationSystem.Web.Models.Customer", b =>
                {
                    b.HasOne("SiteReservationSystem.Web.Models.User", "User")
                        .WithOne("Customer")
                        .HasForeignKey("SiteReservationSystem.Web.Models.Customer", "UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SiteReservationSystem.Web.Models.Employee", b =>
                {
                    b.HasOne("SiteReservationSystem.Web.Models.User", "User")
                        .WithOne("Employee")
                        .HasForeignKey("SiteReservationSystem.Web.Models.Employee", "UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SiteReservationSystem.Web.Models.Invoice", b =>
                {
                    b.HasOne("SiteReservationSystem.Web.Models.Customer", "Customer")
                        .WithMany("Invoices")
                        .HasForeignKey("CustomerID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SiteReservationSystem.Web.Models.Reservation", "Reservation")
                        .WithOne("Invoice")
                        .HasForeignKey("SiteReservationSystem.Web.Models.Invoice", "ReservationID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Reservation");
                });

            modelBuilder.Entity("SiteReservationSystem.Web.Models.Payment", b =>
                {
                    b.HasOne("SiteReservationSystem.Web.Models.Invoice", "Invoice")
                        .WithMany("Payments")
                        .HasForeignKey("InvoiceID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SiteReservationSystem.Web.Models.PaymentMethod", "PaymentMethod")
                        .WithMany("Payments")
                        .HasForeignKey("PaymentMethodID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SiteReservationSystem.Web.Models.Employee", "ProcessedByEmployee")
                        .WithMany("ProcessedPayments")
                        .HasForeignKey("ProcessedByEmployeeID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Invoice");

                    b.Navigation("PaymentMethod");

                    b.Navigation("ProcessedByEmployee");
                });

            modelBuilder.Entity("SiteReservationSystem.Web.Models.Reservation", b =>
                {
                    b.HasOne("SiteReservationSystem.Web.Models.Customer", "Customer")
                        .WithMany("Reservations")
                        .HasForeignKey("CustomerID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SiteReservationSystem.Web.Models.ReservationStatus", "ReservationStatus")
                        .WithMany("Reservations")
                        .HasForeignKey("ReservationStatusID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SiteReservationSystem.Web.Models.Site", "Site")
                        .WithMany("Reservations")
                        .HasForeignKey("SiteID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("ReservationStatus");

                    b.Navigation("Site");
                });

            modelBuilder.Entity("SiteReservationSystem.Web.Models.ReservationFee", b =>
                {
                    b.HasOne("SiteReservationSystem.Web.Models.Fee", "Fee")
                        .WithMany("ReservationFees")
                        .HasForeignKey("FeeID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SiteReservationSystem.Web.Models.Reservation", "Reservation")
                        .WithMany("ReservationFees")
                        .HasForeignKey("ReservationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fee");

                    b.Navigation("Reservation");
                });

            modelBuilder.Entity("SiteReservationSystem.Web.Models.Site", b =>
                {
                    b.HasOne("SiteReservationSystem.Web.Models.SiteType", "SiteType")
                        .WithMany("Sites")
                        .HasForeignKey("SiteTypeID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SiteType");
                });

            modelBuilder.Entity("SiteReservationSystem.Web.Models.SitePhoto", b =>
                {
                    b.HasOne("SiteReservationSystem.Web.Models.Site", "Site")
                        .WithMany("SitePhotos")
                        .HasForeignKey("SiteID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Site");
                });

            modelBuilder.Entity("SiteReservationSystem.Web.Models.SiteTypePricing", b =>
                {
                    b.HasOne("SiteReservationSystem.Web.Models.SiteType", "SiteType")
                        .WithMany("SiteTypePricings")
                        .HasForeignKey("SiteTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SiteType");
                });

            modelBuilder.Entity("SiteReservationSystem.Web.Models.Customer", b =>
                {
                    b.Navigation("Invoices");

                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("SiteReservationSystem.Web.Models.Employee", b =>
                {
                    b.Navigation("ProcessedPayments");
                });

            modelBuilder.Entity("SiteReservationSystem.Web.Models.Fee", b =>
                {
                    b.Navigation("ReservationFees");
                });

            modelBuilder.Entity("SiteReservationSystem.Web.Models.Invoice", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("SiteReservationSystem.Web.Models.PaymentMethod", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("SiteReservationSystem.Web.Models.Reservation", b =>
                {
                    b.Navigation("Invoice");

                    b.Navigation("ReservationFees");
                });

            modelBuilder.Entity("SiteReservationSystem.Web.Models.ReservationStatus", b =>
                {
                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("SiteReservationSystem.Web.Models.Site", b =>
                {
                    b.Navigation("Reservations");

                    b.Navigation("SitePhotos");
                });

            modelBuilder.Entity("SiteReservationSystem.Web.Models.SiteType", b =>
                {
                    b.Navigation("SiteTypePricings");

                    b.Navigation("Sites");
                });

            modelBuilder.Entity("SiteReservationSystem.Web.Models.User", b =>
                {
                    b.Navigation("Admin");

                    b.Navigation("Customer");

                    b.Navigation("Employee");
                });
#pragma warning restore 612, 618
        }
    }
}
